version: '3.9'

services:
  weather-db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=weather
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 30s
      timeout: 2s
      retries: 100
    expose:
      - 3306
    networks:
      - backend

  event-db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=event
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 30s
      timeout: 2s
      retries: 100
    expose:
      - 3306
    networks:
      - backend

  weather:
    build: weather
    environment:
      - DB_HOST=weather-db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - HOST=0.0.0.0
      - PORT=5001
    ports:
      - 5001:5001
    networks:
      - backend
    depends_on:
      weather-db:
        condition: service_healthy

  event:
    build: event
    environment:
      - DB_HOST=event-db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - HOST=0.0.0.0
      - PORT=5002
    ports:
      - 5002:5002
    networks:
      - backend
    depends_on:
      event-db:
        condition: service_healthy

  gateway:
    build: gateway
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      event-db:
        condition: service_healthy
      weather-db:
        condition: service_healthy


networks:
  backend:
    driver: bridge
    name: backend-network